# Generated by Django 5.2.3 on 2025-06-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0002_alter_user_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='company',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
