# Generated by Django 5.2.3 on 2025-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0003_remove_company_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='mm', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
