# Generated by Django 5.2.3 on 2025-06-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0005_remove_customer_business_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
