# Generated by Django 5.2.3 on 2025-06-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0006_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='ddd', max_length=200),
            preserve_default=False,
        ),
    ]
