# Generated by Django 5.2.3 on 2025-06-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0007_customer_full_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='isp_custome_custome_08dbb1_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
