# Generated by Django 5.2.3 on 2025-06-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0008_remove_customer_isp_custome_custome_08dbb1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipment',
            name='identity',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
    ]
