# Generated by Django 5.2.3 on 2025-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0009_networkequipment_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipment',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the equipment, including any specifics'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
