# Generated by Django 5.2.3 on 2025-06-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0010_networkequipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkequipment',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
