# Generated by Django 5.2.3 on 2025-06-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0011_alter_networkequipment_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipment',
            name='auth_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
